project_id            = "cs-host-250323f4c1e749beab0804"
region                = "us-central1"
scheduler_frequency   = "0 12 * * *"
service_account_email = "terraform-poc1@cs-host-250323f4c1e749beab0804.iam.gserviceaccount.com"
bucket_name           = "terraform-harsha-prod-cloud-functions"
source_archive_object = "path/to/prod/function-source.zip"
